/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zerobase.mission1;

public class App {
    public static void main(String[] args) {
        WifiApiController wifiApiController = new WifiApiController();
        wifiApiController.setup();
        wifiApiController.batchWifiInfo();
    }
}
